#using public list provided instead
#server_names = ['cloudflare', 'scaleway-fr', 'yandex']
listen_addresses = ['127.0.0.1:5353', '[::1]:5353']
max_clients = 250
user_name = '_dnscrypt-proxy'

ipv4_servers = true
ipv6_servers = true

dnscrypt_servers = true
doh_servers = true

require_dnssec = true
require_nolog = true
require_nofilter = true


## Uncomment the following line to route all TCP connections to a local Tor node
## Tor doesn't support UDP, so set `force_tcp` to `true` as well.

#proxy = "socks5://127.0.0.1:9050"
#force_tcp = true


timeout = 2500
keepalive = 30
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = false
netprobe_timeout = 60

log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

block_ipv6 = false

cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600


[query_log]
  format = 'tsv'

[nx_log]
  format = 'tsv'

[blacklist]
  log_format = 'tsv'

[ip_blacklist]
  log_format = 'tsv'


[whitelist]
  log_format = 'tsv'

[schedules]
  # some schedule

[sources]

  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = '/var/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

[static]
  # stamp = 'sdns://AgUAAAAAAAAAAAAOZG5zLmdvb2dsZS5jb20NL2V4cGVyaW1lbnRhbA'

